"use client";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import Swal from "sweetalert2";
import ReCAPTCHA from "react-google-recaptcha";
import axios from "axios";
import { CircularProgress } from "@mui/material";
import { useState } from "react";
import RootLayout from "../layout";

function Contact() {
  const [captchaToken, setCaptchaToken] = useState("");
  const [loading, setloading] = useState(false);

  const handleCaptchaChange = (token) => {
    setCaptchaToken(token);
  };
  const [values, setValues] = useState({
    name: "" ,
    email: "" ,
    phone: "" ,
    message: "" 
  });

  const metaData = { 
    title: "Stocks - Equiwiz | Invest in Leading Stocks with Expert Insights",
    description: "Discover stock investment opportunities with Equiwiz. Access expert analysis, track market trends, and invest in leading stocks to build a robust financial portfolio.",
    canonical: "https://equiwiz.com/stocks",
  };
  

  return (
    <RootLayout metadata={metaData}>
      <Layout>
      <>
  <div className="page-banner-wrap bg-cover text-capitalize">
    <div className="container">
      <div className="row">
        <div className="col-12 col-lg-6 offset-lg-3 text-center text-white">
          <div className="page-heading">
            <h1>Stocks</h1>
          </div>
        
        </div>
      </div>
    </div>
  </div>
  {/* banner section end hare */}
  <section className="services-details-wrapper section-padding">
    <div className="container">
      <div className="col-lg-10 col-12 offset-lg-1">
        <div className="services-contents">
          <img src="/assets/img/home/stock.avif" alt="service details image" style={{width:'100%'}} />
          <h3 className="mt-4">
            An automated report is a management tool used by professionals to
            create and share business reports at a specific time information
            each time. These updates are usually made in real-time with the help
            of automated reporting tools.
          </h3>
          <p className="mt-4">
            Data, information, and insights are all around us. Before we even
            realize our business potentials and in our competitive market, there
            is always a new business plan to make, a new strategy to develop, a
            new report to generate - and they all take time. Since amounts of
            data are generated by every second, businesses are always on the
            lookout for the best possible online data analysis tools make their
            processes easier, faster, and more effective.
          </p>
          <p className="mt-4">
            Productivity has become the epitome of successful business
            processes. While every manager seeks how to increase productivity
            and decrease business costs, some invaluable processes can push
            towards sustainable business development - automated reportin and
            systems are the answer you've been looking for.
          </p>
          <p className="mt-4">
            That said, in this post, we will explain what is an automated report
            and its benefits, the ins and outs of the automat process, and
            finish with examples from the real business world. After reading
            this article, you will be equipped to create your own automation
            practic and upscale your reports with the help of a modern online
            reporting software.
          </p>
          <h3 className="mt-5">Working process of trading success</h3>
          <p className="mt-4">
            The trading industry needs continuous automation throughout
            processes, and each part of the company needs to work flawlessly in
            order to avoid potential business issues and cost increment.
          </p>
          <div className="work-process-wrapper">
            <img
              src="/assets/img/service/2.png"
              alt="working process flowchart"
            />
          </div>
          <h3 className="mt-4">Benifits of our Trading Platform:</h3>
          <p className="mt-4">
            Now that we’re up to speed with the concept of automated reporting,
            let’s look at the benefits. First of all, when asking yourself the
            question, “Why should I use report automation?” the short answer
            should be, “why not?”
          </p>
          <ul>
            <li>
              <p>
                <b>Time &amp; cost savings:</b> If you automate reports, you
                will save colossal amounts of time and money on manually
                tracking, updating, and adding data to your reports. Naturally,
                time and money are correlated, so by automating reports, you
                will reap the rewards of valuable data-driven insights while
                empowering your team to place their efforts into more creative
                or strategic activities.
              </p>
            </li>
            <li>
              <p>
                <b>Accessibility, transparency &amp; productivity:</b> By
                serving up automated insights from one central location,
                automatic reports will give everyone in the business the tools
                to perform better in their individual roles while benefiting
                from sharobust, reliable, and accurate.
              </p>
            </li>
            <li>
              <p>
                <b>Real-time decision-making:</b> When using manual reporting
                tools or processes, it’s easy to get bogged down. In addition to
                the more cumbersome reporting processes return data that is
                harder to understand and automated reports, you will gain access
                to accurate data presented in the form of visual.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <section className="cta-banner-wrapper section-padding pt-0">
    <div className="container">
      <div className="cta-banner newsletter-box text-white">
        <div className="row">
          <div className="col-lg-10 offset-lg-1 text-center col-xl-8 offset-xl-2">
            <div className="cta-contents">
              <h2 className="wow fadeInUp">
                Are you interested in doing your project with us?
              </h2>
              <div className="newsletter-form wow fadeInUp">
                <form action="#">
                  <input type="email" placeholder="Enter your email" />
                  <button type="submit" className="submit-btn">
                    Subscribe Now
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</>


      </Layout>
    </RootLayout>
  );
}

export default Contact;
